version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
